### ISSUE TITLE
Error: ENOENT, no such file or directory 'c:\Development\azuread\private.pem'

### ISSUE THREAD

**Issue by radionuch** [AzureADSamples/AzureAD-Node-Sample#6]
Found this (error text below) on first attempt to run app.js .  Any advice?

c:\Development\azuread>node app.js
fs.js:502
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'c:\Development\azuread\private.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Object.<anonymous> (c:\Development\azuread\app.js:28:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by radionuch** [comment]
This error is obviously caused by not providing for a private.pem file.  I commented out that code in app.js as in:
// optional, but required to support SAML logout
    //appUrl: 'http://localhost:3000',
    //logoutCallback: 'http://localhost:3000/logout/callback/',
    //privateCert: fs.readFileSync('./private.pem', 'utf-8'),
    //publicCert: fs.readFileSync('./public.pem', 'utf-8'),

Interestingly, the logout still works.  The env is Office 365 Azure AD with my own admin account.  Login/out tests work error free.
